#!/usr/bin/env perl

use Score;

use UniLang::Agent::Agent;
use UniLang::Util::Message;

$UNIVERSAL::agent = UniLang::Agent::Agent->new
  (Name => "Score",
   ReceiveHandler => \&Receive);
$UNIVERSAL::score = Score->new();

sub Receive {
  my %args = @_;
  $UNIVERSAL::score->ProcessMessage
    (Message => $args{Message});
}

$UNIVERSAL::score->Execute();
